AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  DynamoAtributo:
    Type: String
  NombreDynamo:
    Type: String

Resources:
  DynamoDesdeCero:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        # Esquema de claves para la tabla y los índices
        # !Ref = Parameters
        - AttributeName: !Ref DynamoAtributo
          AttributeType: S
        # S = string
      KeySchema:
        # Clave de partición (HASH)
        - AttributeName: !Ref DynamoAtributo
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      # Facturación por solicitud, sin necesidad de aprovisionar capacidad
      SSESpecification:
        # Cifra la base de datos con cifrado en reposo
        SSEEnabled: true
      TableName: !Ref NombreDynamo
      # Nombre de la tabla, obtenido desde los parámetros

    # Especifica qué hacer con la tabla al eliminar el stack
    DeletionPolicy: Retain
    # 'Retain' evita que la tabla sea eliminada cuando se destruye el stack

# Exportar Nombres
Outputs:
  NombreDynamo:
    Value: !Ref DynamoDesdeCero
    Export:
      Name: NombreDynamo
